version: "3.4"

services:
  lineout:
    image: lineout:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    restart: always
    device_cgroup_rules:
      - 'c 116:* rw'
    volumes:
      - /dev:/dev
    command: ["lineout-player", "/usr/share/sounds/alsa/Front_Center.wav"]

